apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts # note: the oci:// syntax is not included.
    targetRevision: 59.1.0
  destination:
    name: "in-cluster"
    namespace: monitoring
