apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcamp-group-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/cloudcamp-apps/apps
    repoURL: https://github.com/cloudcampla/k8s-application-push.git
    targetRevision: group-apps
